language: ruby
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t johnyxu/docker-react -f Dockerfile.dev .

script:
  - docker run johnyxu/docker-react npm run test -- --coverage
